# Build Wget2

name: Build Wget2 b1

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    container: ghcr.io/ibook86/docker-ubuntu-mingw:main
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          chmod +x build.sh
          /bin/bash ./build.sh
      - uses: actions/upload-artifact@v3
        with:
          name: wget2
          path: /usr/local/x86_64-w64-mingw32/bin/
