# Build Wget2

name: Build

on: push
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Initialization environment
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android
          sudo apt-get -qq update
